//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWSyslog2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWSyslog2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string DefaultSetting_backlogBulkSendCount {
            get {
                return ResourceManager.GetString("DefaultSetting_backlogBulkSendCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 86400.
        /// </summary>
        internal static string DefaultSetting_backlogMaxAge {
            get {
                return ResourceManager.GetString("DefaultSetting_backlogMaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        internal static string DefaultSetting_backlogMaxCount {
            get {
                return ResourceManager.GetString("DefaultSetting_backlogMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 514.
        /// </summary>
        internal static string DefaultSetting_listenPort {
            get {
                return ResourceManager.GetString("DefaultSetting_listenPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string DefaultSetting_messageQueueRevisitDelay {
            get {
                return ResourceManager.GetString("DefaultSetting_messageQueueRevisitDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Service_Autolog {
            get {
                return ResourceManager.GetString("Service_Autolog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Service_CanPauseAndContinue {
            get {
                return ResourceManager.GetString("Service_CanPauseAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Service_CanStop {
            get {
                return ResourceManager.GetString("Service_CanStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring service for Syslog network events from the local gateway&apos;s firewall..
        /// </summary>
        internal static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Syslog Recorder 2.
        /// </summary>
        internal static string Service_Name {
            get {
                return ResourceManager.GetString("Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Syslog Recorder 2.
        /// </summary>
        internal static string WindowsEventLog_AppName {
            get {
                return ResourceManager.GetString("WindowsEventLog_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the configuration file has misplaced elements or is otherwise damaged.
        /// </summary>
        internal static string WindowsEventLog_ConfigError_AppConfigFormatError {
            get {
                return ResourceManager.GetString("WindowsEventLog_ConfigError_AppConfigFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the setting definition was missing from the &apos;appSettings&apos; section.
        /// </summary>
        internal static string WindowsEventLog_ConfigError_AppConfigMissingEntry {
            get {
                return ResourceManager.GetString("WindowsEventLog_ConfigError_AppConfigMissingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were one or more critical errors while loading configuration settings during service startup.  Service startup has failed.  Details below..
        /// </summary>
        internal static string WindowsEventLog_ConfigError_CriticalPreface {
            get {
                return ResourceManager.GetString("WindowsEventLog_ConfigError_CriticalPreface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the data was malformed.
        /// </summary>
        internal static string WindowsEventLog_ConfigError_MalformedData {
            get {
                return ResourceManager.GetString("WindowsEventLog_ConfigError_MalformedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were one or more errors while loading configuration settings from the App.config file during service startup.  The service has started with default values for affected settings.  Details below..
        /// </summary>
        internal static string WindowsEventLog_ConfigError_WarningPreface {
            get {
                return ResourceManager.GetString("WindowsEventLog_ConfigError_WarningPreface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string WindowsEventLog_GroupName {
            get {
                return ResourceManager.GetString("WindowsEventLog_GroupName", resourceCulture);
            }
        }
    }
}
